In [1]:
!pip install tensorflow==1.8.0

     |████████████████████████████████| 49.1MB 84kB/s 
     |████████████████████████████████| 3.1MB 56.7MB/s 
     |████████████████████████████████| 890kB 43.7MB/s 
  Created wheel for html5lib: filename=html5lib-0.9999999-cp36-none-any.whl size=107220 sha256=e068b47dd2bda8998180dc9df3fb5cee44b1e48eeef9b93e3cf1abe971a8501c
  Stored in directory: /root/.cache/pip/wheels/50/ae/f9/d2b189788efcf61d1ee0e36045476735c838898eef1cad6e29
Successfully built html5lib
  Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Found existing installation: bleach 3.1.5
    Uninstalling bleach-3.1.5:
      Successfully uninstalled bleach-3.1.5
  Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninstalled tensorboard-2.3.0
  Found existing installation: tensorflow 2.3.0
    Uninstalling tensorflow-2.3.0:
      Successfully uninstalled tensorflow-2.3.0


In [1]:
import tensorflow as tf

tf.__version__

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or 

'1.8.0'

In [2]:
hello = tf.constant('Hello Tensorflow!')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [3]:
a = tf.constant(10)
b = tf.constant(23)
c = tf.add(a, b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [6]:
sess = tf.Session()

print(sess.run(hello))
print(sess.run([a,b,c]))

sess.close()

b'Hello Tensorflow!'
[10, 23, 33]


In [7]:
X = tf.placeholder(tf.float32,[None,3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [8]:
x_data = [[1,2,3],[4,5,6]]

In [9]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

In [10]:
expr = tf.matmul(X,W) + b

In [11]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X: x_data}))
sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[ 0.13295     0.19532321]
 [-1.053838    0.6812584 ]
 [ 0.07066993 -0.74535877]]
=== b ===
[[-0.8083832]
 [ 1.6995168]]
=== expr ===
[[-2.5710995 -1.4866196]
 [-2.6138535  1.4149489]]


In [12]:
# Simple Linear Regression

x_data = [1, 2, 3]
y_data = [1, 2, 3]

W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")
print(X)
print(Y)

Tensor("X:0", dtype=float32)
Tensor("Y:0", dtype=float32)


In [13]:
hypothesis = W * X + b

In [14]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [15]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)

In [16]:
train_op = optimizer.minimize(cost)

In [18]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data})

        print(step, cost_val, sess.run(W), sess.run(b))

    print("\n=== Test ===")
    print("X: 5, Y:", sess.run(hypothesis, feed_dict={X: 5}))
    print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X: 2.5}))

0 4.3867874 [1.1890832] [-0.18865547]
1 0.05974945 [1.0880677] [-0.22655769]
2 0.007713026 [1.0964942] [-0.2164732]
3 0.006758963 [1.0930222] [-0.21177626]
4 0.006430877 [1.090912] [-0.20662989]
5 0.0061253253 [1.0887127] [-0.20166871]
6 0.0058343685 [1.0865817] [-0.19682004]
7 0.0055572297 [1.0845001] [-0.19208871]
8 0.0052932627 [1.0824687] [-0.187471]
9 0.005041828 [1.0804863] [-0.1829643]
10 0.004802332 [1.0785515] [-0.17856595]
11 0.0045742188 [1.0766631] [-0.17427337]
12 0.0043569384 [1.0748203] [-0.17008395]
13 0.00414998 [1.0730217] [-0.16599527]
14 0.00395285 [1.0712662] [-0.16200487]
15 0.0037650887 [1.069553] [-0.15811037]
16 0.0035862506 [1.067881] [-0.15430951]
17 0.0034158928 [1.0662493] [-0.1506]
18 0.0032536378 [1.0646566] [-0.1469797]
19 0.0030990818 [1.0631024] [-0.1434464]
20 0.0029518828 [1.0615854] [-0.13999806]
21 0.0028116691 [1.0601048] [-0.13663262]
22 0.0026781065 [1.05866] [-0.13334803]
23 0.002550897 [1.0572499] [-0.13014245]
24 0.0024297235 [1.0558736] [-0.